CREATE TABLE SQMS_PRIVATE_1231.WORKSTATUS
(
  STATUSID      VARCHAR2(40)                    NOT NULL,
  EMPID         VARCHAR2(40),
  EQUID         VARCHAR2(40),
  STARTUPTIME   DATE,
  SHUTDOWNTIME  DATE,
  CREATED       DATE,
  CREATEDBY     VARCHAR2(40),
  MODIFIED      DATE,
  MODIFIEDBY    VARCHAR2(40),
  ISVOID        CHAR(1)
)
TABLESPACE SQMS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE SQMS_PRIVATE_1231.WORKSTATUS ADD (
  CONSTRAINT WORKSTATUS_PK
 PRIMARY KEY
 (STATUSID));

ALTER TABLE SQMS_PRIVATE_1231.WORKSTATUS ADD (
  CONSTRAINT WORKSTATUS_R01 
 FOREIGN KEY (EMPID) 
 REFERENCES SQMS_PRIVATE_1231.EMPLOYEE (EMPID),
  CONSTRAINT WORKSTATUS_R02 
 FOREIGN KEY (EQUID) 
 REFERENCES SQMS_PRIVATE_1231.EQUIPMENT (EQUID));

